matrix:
  homeserverUrl: "https://dev.t2bot.io"
  accessToken: "MDAxYWxvY2F0aW9uIGRldi50MmJvdC5pbwowMDEzaWRlbnRpZmllciBrZXkKMDAxMGNpZCBnZW4gPSAxCjAwMjZjaWQgdXNlcl9pZCA9IEBlbWFpbDpkZXYudDJib3QuaW8KMDAxNmNpZCB0eXBlID0gYWNjZXNzCjAwMjFjaWQgbm9uY2UgPSA3Ry1odVFPXiZZQEEjMWkwCjAwMmZzaWduYXR1cmUgArUOQrynyxLZlJogJ9yEpDfGZoqVeh9dHOVmNBwttU8K"
  userId: "@email:dev.t2bot.io"
mail:
  port: 25
  domain: "email.dev.t2bot.io"
web:
  port: 3000
  bindIp: '0.0.0.0'
customMailTargets:
  "test@email.dev.t2bot.io":
  - "!fpGTgjOETMkRESGXcN:dev.t2bot.io"
defaultRoomConfig:
  allowFromAnyone: true
  allowedSenders: []
  blockedSenders: []
  skipDatabase: false
  useCcAsTarget: true
  useBccAsTarget: true
  useToAsTarget: true
  plaintextOnly: false
  messageFormat: "$subject: <a href='http://localhost:3000/m/$id'>Click to view</a><br>$text_body"
roomConfigs:
  "!fpGTgjOETMkRESGXcN:dev.t2bot.io":
    allowFromAnyone: false
    allowedSenders: ["travpc@gmail.com"]
    blockedSenders: []
